# permissions for end users to view fulfillstorageclassclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fulfillstorageclassclaim-viewer-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - fulfillstorageclassclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - fulfillstorageclassclaims/status
  verbs:
  - get
